### ISSUE TITLE
Bug with @Timeout and @Fallback

### ISSUE THREAD

**Issue by brunobat** [smallrye/smallrye-fault-tolerance#89] opened 2019-05-15 13:49 UTC
When using:
    @Fallback(fallbackMethod = "fallback") 
    @Timeout(500)
On a rest endpoint I found the fallback is executed upfront. The 500ms wait time is disregarded.
You can reproduce the issue by uncommenting this line:

https://github.com/brunobat/java-framework-compare/blob/1f5621ed596d5ad6e5eb24382966cb7b15b7895b/quarkus/src/main/java/org/acme/rest/json/LegumeResource.java#L38

and executing this test:

https://github.com/brunobat/java-framework-compare/blob/1f5621ed596d5ad6e5eb24382966cb7b15b7895b/quarkus/src/test/java/org/acme/rest/json/LegumeResourceTest.java#L18

**Comment by Ladicek** [comment] 2019-05-15 13:52
Will try, thanks!

**Comment by Ladicek** [comment] 2019-05-16 15:52
This might be caused by us always executing `@Timeout` methods on an extra thread. Will need to take a deeper look.

**Comment by Ladicek** [comment] 2019-05-16 16:11
Ah yeah. The fallback is triggered by an underlying exception `javax.enterprise.context.ContextNotActiveException: interface javax.enterprise.context.RequestScoped`, and that's because we execute the timeout action on an extra thread.

**Comment by Ladicek** [comment] 2020-01-03 14:18
This should be addressed in the new implementation, which will most likely be called 4.0.0.

**Comment by Ladicek** [comment] 2020-01-15 08:35
New implementation has been merged to `master`, hence closing this.

**Closed by Ladicek** 2020-01-15 08:35 UTC
